-- Databricks notebook source
SET TIME ZONE 'Etc/UTC';
CREATE OR REPLACE VIEW TUONG AS (SELECT to_timestamp('2021-09-26 02:00:00') as T1, to_timestamp('2021-09-26 03:00:00') as T2);
SELECT * FROM TUONG

-- COMMAND ----------

SET TIME ZONE 'Pacific/Auckland';
SELECT * FROM TUONG

-- COMMAND ----------

-- DBTITLE 1,EXAMPLE WITH TIMESTAMP UTC
SET TIME ZONE 'Etc/UTC';
SELECT TO_TIMESTAMP('2022-04-02 14:30') as UTC,
CURRENT_TIMESTAMP as NOW, 
CURRENT_TIMESTAMP - INTERVAL 10 MINUTE AS TEN_MINUTES_AGO, 
CURRENT_TIMESTAMP - INTERVAL 1 DAY AS ONE_DAY_AGO, 
CURRENT_TIMESTAMP - INTERVAL 1 WEEK AS ONE_WEEK_AGO, 
CURRENT_TIMESTAMP - INTERVAL 1 MONTH  AS ONE_MONTH_AGO,
CURRENT_TIMESTAMP - INTERVAL 1 YEAR  AS ONE_YEAR_AGO;


-- COMMAND ----------

-- DBTITLE 1,EXAMPLE WITH TIMESTAMP NZT
SET TIME ZONE 'Pacific/Auckland';
SELECT TO_TIMESTAMP('2022-04-03 02:30') as NZT,
TO_TIMESTAMP('2022-04-03 02:30') + INTERVAL 1 HOUR as NZT1,
CURRENT_TIMESTAMP as NOW, 
CURRENT_TIMESTAMP - INTERVAL 10 MINUTE AS TEN_MINUTES_AGO, 
CURRENT_TIMESTAMP - INTERVAL 1 DAY AS ONE_DAY_AGO, 
CURRENT_TIMESTAMP - INTERVAL 1 WEEK AS ONE_WEEK_AGO, 
CURRENT_TIMESTAMP - INTERVAL 1 MONTH  AS ONE_MONTH_AGO,
CURRENT_TIMESTAMP - INTERVAL 1 YEAR  AS ONE_YEAR_AGO;
